language: go

go:
  - "1.10.x"

matrix:
    include:
        - os: linux
          before_install:
              - sudo add-apt-repository ppa:webkit-team/ppa -y
              - sudo apt-get update
              - sudo apt-get install libwebkit2gtk-4.0-dev -y

install:
    - make init

script:
    - make linux
